version: '3'

services:
  # Servicio de Jira
  jira:
    build:
      context: .  # El contexto de construcción es el directorio actual, donde está el Dockerfile
    container_name: jira
    environment:
      - ATLASSIAN_JIRA_LICENSE=SEN-74290435
      - ATLASSIAN_JIRA_HOME=/var/atlassian/application-data/jira
      - ATLASSIAN_DB_TYPE=mysql
      - ATLASSIAN_DB_HOST=mysql
      - ATLASSIAN_DB_PORT=3306
      - ATLASSIAN_DB_USER=jirauser
      - ATLASSIAN_DB_PASSWORD=jiradatabasepassword
      - ATLASSIAN_DB_NAME=jiradb
    ports:
      - "8080:8080"  # Exponer Jira al exterior en el puerto 8080
    networks:
      - internal_network
    volumes:
      - ./jira-data:/var/atlassian/application-data/jira
    restart: always

  # Servicio de MySQL
  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=rootpassword
      - MYSQL_DATABASE=jiradb
      - MYSQL_USER=jirauser
      - MYSQL_PASSWORD=jiradatabasepassword
    networks:
      - internal_network
    volumes:
      - ./mysql-data:/var/lib/mysql
    restart: always

  # Servicio de PHPMyAdmin
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin
    environment:
      - PMA_HOST=mysql
      - PMA_PORT=3306
    ports:
      - "8081:80"  # Exponer PHPMyAdmin al exterior en el puerto 8081
    networks:
      - internal_network
    restart: always

networks:
  internal_network:
    driver: bridge

volumes:
  jira-data:
    driver: local
  mysql-data:
    driver: local