version: '3'

services:
  # Contenedor de Nginx Proxy (para redirigir tráfico HTTP y HTTPS)
  nginx-proxy:
    image: jwilder/nginx-proxy
    container_name: nginx-proxy
    environment:
      - DEFAULT_HOST=www.atlassian.jira.avisonline.store  # Tu dominio
      - NGINX_PROXY_READ_TIMEOUT=600
      - NGINX_PROXY_CONNECT_TIMEOUT=600
      - NGINX_PROXY_SEND_TIMEOUT=600
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - /usr/share/nginx/html:/usr/share/nginx/html  # Agregar esta línea
      - nginx_certs:/etc/nginx/certs  # Volumen persistente para certificados
    networks:
      - internal_network
    restart: always

  # Contenedor de Let's Encrypt para manejar certificados SSL
  letsencrypt-nginx-proxy-companion:
    image: jrcs/letsencrypt-nginx-proxy-companion
    container_name: letsencrypt-nginx-proxy-companion
    environment:
      - NGINX_PROXY_CONTAINER=nginx-proxy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /usr/share/nginx/html:/usr/share/nginx/html  # Agregar esta línea
      - nginx_certs:/etc/nginx/certs  # Volumen persistente para certificados
    networks:
      - internal_network
    restart: always

  # Servicio de Jira
  jira:
    build:
      context: .  # El contexto de construcción es el directorio actual, donde está el Dockerfile
    container_name: jira
    environment:
      - ATLASSIAN_JIRA_LICENSE=SEN-74290435
      - ATLASSIAN_JIRA_HOME=/var/atlassian/application-data/jira
      - ATLASSIAN_DB_TYPE=mysql
      - ATLASSIAN_DB_HOST=mysql
      - ATLASSIAN_DB_PORT=3306
      - ATLASSIAN_DB_USER=jirauser
      - ATLASSIAN_DB_PASSWORD=jiradatabasepassword
      - ATLASSIAN_DB_NAME=jiradb
      - VIRTUAL_HOST=www.atlassian.jira.avisonline.store  # Tu dominio
      - LETSENCRYPT_HOST=www.atlassian.jira.avisonline.store  # Tu dominio
      - LETSENCRYPT_EMAIL=nolberto.sumaran@gmail.com # Cambia esto por tu email
    networks:
      - internal_network
    volumes:
      - ./jira-data:/var/atlassian/application-data/jira
    restart: always

  # Servicio de MySQL
  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=rootpassword
      - MYSQL_DATABASE=jiradb
      - MYSQL_USER=jirauser
      - MYSQL_PASSWORD=jiradatabasepassword
    networks:
      - internal_network
    volumes:
      - ./mysql-data:/var/lib/mysql
    restart: always

  # Servicio de PHPMyAdmin
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin
    environment:
      - PMA_HOST=mysql
      - PMA_PORT=3306
    ports:
      - "8081:80"  # Exponer PHPMyAdmin en el puerto 8081
    networks:
      - internal_network
    restart: always

networks:
  internal_network:
    driver: bridge

volumes:
  nginx_certs:
    driver: local
  jira-data:
    driver: local
  mysql-data:
    driver: local
